### PR TITLE
Implement Better Auth

### PR DESCRIPTION
**Pull request by cameronapak**
An incomplete, but close implementation of Better Auth https://www.better-auth.com/docs/installation

Contributions are welcomed!

### CODE REVIEW

**Comment by cameronapak** [comment]
Got the auth working! Just need to add a few more things to make the experience of using this easier

**Review by cameronapak — COMMENTED** [review]
LGTM, me!

**Comment by Lftobs** [comment]
I don't know if it's only on my end but I can't sign in .... Seems sign in ain't working

**Comment by cameronapak** [comment]
You will need to create a new account, if you haven't already. Please make sure you have the right ENV variables, too. https://www.better-auth.com/docs/installation#set-environment-variables

Can be any random secret key

and then http://localhost4321

**Comment by Lftobs** [comment]
I tried it on the live site tho.... Great work btw

**Comment by cameronapak** [comment]
> I tried it on the live site tho.... Great work btw

Thanks for letting me know. I found a couple of reasons why it was acting goofy and think I fixed it. Try again and let me know if it works or doesn't work. Thanks!

**Pull request merged**
